title: Siu Yuen Kevin Chow # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A newcomer to the field of data science and machine learning, with 3+ years of experience in financial markets and banking. Graduated from The Hong Kong University of Science and Technology. Previously at Everbright Securities International, The Bank of East Asia, Bank of China (Hong Kong). 
  <br><br>
  Certificates: <br>
  MIT Professional Education Applied Data Science Program, IBM Data Science Professional Certificate, AWS Certified Cloud Practitioner.
  <br><br>
  <a href="https://www.linkedin.com/in/siuyuenchow/">View My LinkedIn Profile</a> 
 
theme: jekyll-theme-minimal
