title: Kevin Chow # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>About me:</b><br>
  As a passionate data enthusiast, I am actively pursuing opportunities in the dynamic field of data analytics. With over 3 years of experience in financial markets and banking, I have honed my skills at prominent institutions such as Everbright Securities International, The Bank of East Asia, and Bank of China (Hong Kong). I am a proud graduate of The Hong Kong University of Science and Technology, where I acquired a strong foundation to support my journey in the world of data. 
  <br><br>
  <b>Certificates:</b><br>
  MIT Professional Education Applied Data Science Program <br>
  IBM Data Science Professional Certificate <br>
  AWS Certified Cloud Practitioner <br>
  <br>
  <a href="https://www.linkedin.com/in/siuyuenchow/">View My LinkedIn Profile</a>
  <br>
  <a href="https://github.com/Kevin-qt/">View My GitHub Profile</a>
  <br>
  <a href="https://kevinchow.org/">View My Technical Blog</a> 
 
theme: jekyll-theme-minimal
